spring:
  security:
    user:
      name: admin
      password: admin
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://admin:admin@127.0.0.1:8761/eureka

server:
  port: 8761
